permalink: pretty
cdn: https://grads.images.algonquindesign.ca/2016/

collections:
  grads:
    output: true
    permalink: /grads/:path/
    title: "Grads"

exclude:
  - README.md
  - .editorconfig
  - .gitignore

kramdown:
  input: GFM

baseurl: ""
