permalink: pretty
cdn: http://grads.images.algonquindesign.ca.s3.amazonaws.com/2016/

# http://grads.images.algonquindesign.ca/2016

collections:
  grads:
    output: true
    permalink: /grads/:path/
    title: "Grads"

exclude:
  - README.md
  - .editorconfig
  - .gitignore

kramdown:
  input: GFM

baseurl: /2016
